### ISSUE TITLE
Matches endpoint doesn't support offseason events

### ISSUE THREAD

**Issue by William5553** [avgupta456/statbotics#337]
The `/v2/matches/event/{event}` endpoint doesn't support offseason events, for example, [api.statbotics.io/v2/matches/event/2023iri](https://api.statbotics.io/v2/matches/event/2023iri) returns an empty array. However, checking individual matches does work ([api.statbotics.io/v2/match/2023iri_f1m1](https://api.statbotics.io/v2/match/2023iri_f1m1)).

**Comment by avgupta456** [comment]
Sorry about that! The default filtering excludes offseason events, even if the event is an offseason event. For now, can you use this endpoint instead: `https://api.statbotics.io/v2/matches?event=2022iri&offseason=True`.

I'm working on v3 of the API right now. I'll keep this issue open so I can make sure this edge case is fixed.
