### ISSUE TITLE
Hypothetical events broken - unhashable type list

### ISSUE THREAD

**Issue by tervay** [avgupta456/statbotics#371]
Seems hypothetical events are broken. For example

https://www.statbotics.io/event/O00ly04431X1nDY2t6puU_woxWysBiDo_j8HIud5H2dTRAzt9rViFVF1Ep-HWPYOZOZmcreUesfUgUhdmynenjpqqWtGv0xczkWgGLuBa6c9F4-YnniutSWEHDAUbLpAPbjIkf_LKhFMKBDbgordQrjXtFBiryh05W9maunCRcHNIJgGrRQxj-l0heFrYwuTZVQ_qtyh-O_TGmiGg

The console shows a GET request to

https://api.statbotics.io/site/event/hypothetical/O00ly04431X1nDY2t6puU_woxWysBiDo_j8HIud5H2dTRAzt9rViFVF1Ep-HWPYOZOZmcreUesfUgUhdmynenjpqqWtGv0xczkWgGLuBa6c9F4-YnniutSWEHDAUbLpAPbjIkf_LKhFMKBDbgordQrjXtFBiryh05W9maunCRcHNIJgGrRQxj-l0heFrYwuTZVQ_qtyh-O_TGmiGg

which responds with

```json
{"data":[],"message":"Error unhashable type: 'list'","time":"PT0.07222S"}
```

**Comment by avgupta456** [comment]
Should be fixed now, thanks for the bug report!
