### ISSUE TITLE
Access control error for EPA over time

### ISSUE THREAD

**Issue by Lyanthropos** [avgupta456/statbotics#373]
As seen in the recording below, attempting to select a team in the EPA over time causes a promise rejection due to access control checks (likely CORS related).

https://github.com/avgupta456/statbotics/assets/11381726/273e10ab-c582-4390-b466-aff191eee968

**Comment by Lyanthropos** [comment]
I'd be happy to debug and fix this myself if you want another volunteer dev – my job is doing essential this for the University of Minnesota.

**Comment by avgupta456** [comment]
Should be fixed now, thanks for the bug report!
